"use client";

export default function ComplianceClient() {
  return (
    <div className="min-h-screen bg-[#05050a] font-sans text-white">
      <div className="mx-auto w-full max-w-md px-4 pb-16 pt-24 sm:max-w-xl lg:max-w-4xl">
        <h1 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl">
          18 U.S.C. &sect; 2257 Record Keeping Requirements Compliance Statement
        </h1>

        <p className="mt-6 text-sm leading-7 text-white/70">
          The operator of Dzzzs.com is not the producer (whether primary or secondary as defined in 18 U.S.C. &sect; 2257) of any of the content found on Dzzzs.com. Our activities are limited to the transmission, storage, retrieval, hosting, and/or formatting of text-to-image or text-to-video conversions generated by third-party users (&ldquo;Verified Users&rdquo;).
        </p>

        <section className="mt-8">
          <h2 className="text-xl font-semibold text-white">Exemption: Content Produced by Third Parties</h2>
          <p className="mt-3 text-sm leading-7 text-white/70">
            All portions of the website containing user-generated material are under the control of the relevant Verified User, for whom this platform is provided as an online service. Pursuant to 18 U.S.C. &sect; 2257(h)(2)(B)(v) and 47 U.S.C. &sect; 230(c), Dzzzs.com reserves the right to delete materials that are deemed, in our sole discretion, to be inconsistent with our Terms of Service.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-xl font-semibold text-white">Exemption: Content Produced by Website Operators</h2>
          <p className="mt-3 text-sm leading-7 text-white/70">
            For the avoidance of doubt, no images appearing on this website depict actual human beings. Furthermore, no images uploaded by users, nor any images generated by users that are derived from or based upon images uploaded by users, are ever displayed on this website. All visual depictions are synthesized through artificial intelligence algorithms and are therefore exempt from the requirements of 18 U.S.C. &sect; 2257 and 28 C.F.R. &sect; 75.
          </p>
        </section>

        <section className="mt-8">
          <h2 className="text-xl font-semibold text-white">Designated Records Custodian</h2>
          <p className="mt-3 text-sm leading-7 text-white/70">
            While we do not produce the content, we have designated a custodian to be the keeper of original records for all marketing and advertising materials that are within the scope of 18 U.S.C. &sect; 2257 and 28 C.F.R. &sect; 75. The aforementioned records and their custodian can be found at the following location:
          </p>
          <p className="mt-3 text-sm leading-7 text-white/70">Dzzzs.com</p>
        </section>

        <section className="mt-8">
          <h2 className="text-xl font-semibold text-white">Age Verification and Compliance Procedures</h2>
          <ol className="mt-3 list-decimal space-y-2 pl-5 text-sm leading-7 text-white/70">
            <li>All Verified Users must be over eighteen (18) years of age. They are personally identified and verified by Dzzzs.com prior to generating, sharing, and displaying content.</li>
            <li>Verified Users must provide evidence or certify that all AI-generated depictions are compliant with age and consent requirements, as well as record-keeping requirements under 18 U.S.C. &sect; 2257.</li>
          </ol>
        </section>

        <p className="mt-8 text-sm leading-7 text-white/70">
          For further assistance or questions regarding this notice, please contact our compliance department at support@dzzzs.com
        </p>
      </div>
    </div>
  );
}
